### ISSUE TITLE
what we should try out first

### ISSUE THREAD

**Issue by devilhtc** [devilhtc/EE367-livephoto#3]
My suggestion is to first do fine segmentation. To do this, we probably need to 
- [ ] #4 calculate optical flow (there are several state-of-the-art methods such as epicflow or deepflow. Deepflow should has api in opencv 3 but epicflow only has source code in C++).
- [ ] #5 (this might be less important) find way to smooth optical flow across frames
- [ ] #6 do clustering in some feature space (containing flow, color, position etc) using clustering algorithms (such as primitive k-means or mean-shift?)

**Comment by valkjsaaa** [comment]
Aggred.
